### ISSUE TITLE
After a couple of days, screensaver stops updating

### ISSUE THREAD

**Issue by anacommsystems** [13mralex/c4-android-screensaver#1]
this screensaver is great! but after a day or so, the time will stop updating. When I tap the screen to put up the C4 app, when it goes back to the screensaver the time says that the time it went to it. the only way i've found is to physically reset the EA3 i'm using and it'll go back to working for about a day, then it'll have to be reset again

**Comment by Kamol81** [comment]
For me to. I have bought app called Dashboard Screen Saver https://play.google.com/store/apps/details?id=chyzinr.webpagescreensaver&hl=en_US
You can set there time to update url for 60 seconds to keep data sync

**Comment by 13mralex** [comment]
This is fixed now. A director reboot caused some project information not to load, causing the weather to error out and halt the script on the web side.
